//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace crudapp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RozkladJazdyKMEntities : DbContext
    {
        public RozkladJazdyKMEntities()
            : base("name=RozkladJazdyKMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<czasyodjazdow> czasyodjazdow { get; set; }
        public virtual DbSet<dni> dni { get; set; }
        public virtual DbSet<przejazdy> przejazdy { get; set; }
        public virtual DbSet<przystanki> przystanki { get; set; }
        public virtual DbSet<relacje> relacje { get; set; }
        public virtual DbSet<rodzajelinii> rodzajelinii { get; set; }
    }
}
