//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace crudapp
{
    using System;
    using System.Collections.Generic;
    
    public partial class przejazdy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public przejazdy()
        {
            this.czasyodjazdow = new HashSet<czasyodjazdow>();
        }
    
        public short idprzejazdu { get; set; }
        public Nullable<short> idrelacji { get; set; }
        public Nullable<short> idprzystanku { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<czasyodjazdow> czasyodjazdow { get; set; }
        public virtual przystanki przystanki { get; set; }
        public virtual relacje relacje { get; set; }
    }
}
