//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace crudapp.BazaDanych
{
    using System;
    using System.Collections.Generic;
    
    public partial class czasyodjazdow
    {
        public Nullable<short> idprzejazdu { get; set; }
        public Nullable<short> dni { get; set; }
        public Nullable<System.TimeSpan> czas { get; set; }
        public int idczasu { get; set; }
    
        public virtual dni dni1 { get; set; }
        public virtual przejazdy przejazdy { get; set; }
    }
}
