//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace crudapp.BazaDanych
{
    using System;
    using System.Collections.Generic;
    
    public partial class dni
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public dni()
        {
            this.czasyodjazdow = new HashSet<czasyodjazdow>();
        }
    
        public short idDni { get; set; }
        public string tydzien { get; set; }
        public Nullable<bool> czynocny { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<czasyodjazdow> czasyodjazdow { get; set; }
    }
}
