//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace crudapp.BazaDanych
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class relacje
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public relacje()
        {
            this.przejazdy = new ObservableCollection<przejazdy>();
        }
    
        public short idrelacji { get; set; }
        public Nullable<short> numerlinii { get; set; }
        public Nullable<short> idpierwszegoprzystanku { get; set; }
        public Nullable<short> idostatniegoprzystanku { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<przejazdy> przejazdy { get; set; }
        public virtual przystanki przystanki { get; set; }
        public virtual przystanki przystanki1 { get; set; }
        public virtual rodzajelinii rodzajelinii { get; set; }
    }
}
